server:
  port: 8080
spring:
  application:
    name: user-consume
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 1487792164@qq.com
    password: ieyntpbagikhbahb  # 你的授权码
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  rabbitmq:
    host: 192.168.253.129 #我的虚拟机ip
    port: 5672
    username: guest #默认
    password: guest #默认

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

server.name: user-service

corp:
  agentid: 1000002
  corpid: ww475076ea132157f1
  corpsecret: jhGMY5CLGhJ_bjJ-hsoK5QOSMPujYtG18I23mEJbOT4