server:
  port: 8089
spring:
  application:
    name: kafka-demo

  kafka:
    # 连接kafka集群
    bootstrap-servers: 192.168.253.129:19092,192.168.253.129:29092,192.168.253.129:39092
    producer:
      # key和value的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # key和value的反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # group-id: kafka-test # 同一组的消费实例，会负载消费消息。此处不配置group-id，则消费监听注解上须指定group-id，否则启动报错
      # properties:
      # partitioner.class: # 自定义分区

eureka:
  client:
    service-url: # eureka的地址信息
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/


